#!/usr/bin/env python3
""" fix movie for mini 4k / freebox + kodi  + minidlna """
import logging
import subprocess
import os
import sys
import argparse
import json
import zipfile
# import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup

# ffprobe -loglevel quiet -show_entries stream=index,codec_name,codec_type:stream_tags=language -i /tmp/toto.mkv


class FfmpegHelper(object):

    """
    """

    def __init__(self, input_file, output_dir='/tmp/dbg'):
        self.logger = self._get_logger()
        self.input_file = input_file
        self.output_dir = output_dir
        self.ffprobe_command = 'ffprobe'
        self.ffprobe_data = None
        self.ffmpeg_command = 'ffmpeg'
        self.genpts = False
        self.packed_bframes = False
        self.verbose = False

    def set_verbose(self, verbose):
        self.verbose = verbose

    def _raise_exception(self, message):
        if bool(self.nfo):
            self.logger.error(self.nfo.prettify())
        if bool(self.ffprobe_data):
            self.logger.error(json.dumps(self.ffprobe_data, indent=4))
        self.logger.error(message)
        raise Exception(message)

    def _grab_info(self):
        """ Inspect info of AVI file for basic check
        """
        filename, file_extension = os.path.splitext(self.input_file)
        self.nfo_file = filename + '.nfo'
        with open(self.nfo_file) as nfo_xml:
            self.nfo = BeautifulSoup(nfo_xml, 'lxml')
        command_line = [self.ffprobe_command, '-hide_banner', '-show_streams',
                        '-show_format', '-print_format', 'json', '-i', self.input_file]
        if not self.verbose:
            command_line.extend(['-v', 'error'])
        errcode, stdout, stderr = self.call_process(command_line, nolog=True)
        self.ffprobe_data = json.loads(stdout)
        if self.verbose:
            self.logger.info(json.dumps(self.ffprobe_data, indent=4))

    def _check_genpts(self):
        command_line = [self.ffmpeg_command, '-hide_banner', '-y', '-v', 'error', '-i',
                        self.input_file, '-ss', '0', '-t', '1', '-an', '-c:v', 'copy', '-f', 'matroska', '/dev/null']
        errcode, stdout, stderr = self.call_process(
            command_line, nolog=True, noerr=True)
        if 'unknown timestamp' in stderr:
            self.genpts = True

    def _check_packed_bframes(self):
        command_line = [self.ffmpeg_command, '-hide_banner', '-y',
                        '-v', 'info', '-i', self.input_file, '-ss', '0', '-t', '1', '-an', '-c:v', 'mpeg4', '-f', 'null', '/dev/null']
        errcode, stdout, stderr = self.call_process(command_line, nolog=True)
        if 'mpeg4_unpack_bframes' in stderr:
            self.packed_bframes = True

    def _check_info(self):
        # Technical limitation:
        nb_streams = self.ffprobe_data['format']['nb_streams']
        if nb_streams != 1 and nb_streams != 2:
            self._raise_exception(
                "Invalid nb_streams value: %d" % nb_streams)

        # single stream, should be video:
        codec_type = self.ffprobe_data['streams'][0]['codec_type']
        codec_types = sorted([stream['codec_type']
                              for stream in self.ffprobe_data['streams']])
        if codec_types != ['video'] and ['audio', 'video'] != codec_types:
            self._raise_exception(
                "Codec Types are Unhandled: %s" % codec_types)

    def _convert(self, out_ext):
        filename, file_extension = os.path.splitext(self.input_file)
        command_line = [self.ffmpeg_command, '-hide_banner', '-y']
        if not self.verbose:
            command_line.extend(['-v', 'error'])
        if self.genpts:
            command_line.extend(['-fflags', '+genpts'])
        command_line.extend(['-i', self.input_file])
        title = self.nfo.title.string
        date = self.nfo.year.string
        # Asterix.Cesar-poster.jpg
        poster = filename + '-poster.jpg'
        # -i *Dumbo*poster* -disposition:v:1 attached_pic -map 0 -map 1
        command_line.extend(
            ['-i', poster, '-disposition:v:1', 'attached_pic', '-map', '0', '-map', '1'])
        command_line.extend(['-map_metadata', '0'])
        command_line.extend(['-map_metadata:s:v:0', '-1'])
        command_line.extend(['-map_chapters', '0'])
        command_line.extend(['-metadata:s:a:0', 'language=fre'])
        command_line.extend(['-metadata:s:a:0', 'title=audio title'])
        command_line.extend(['-disposition:a:0', 'default'])
        command_line.extend(['-metadata:s:v:0', 'language=fre'])
        command_line.extend(['-metadata:s:v:1', 'language=fre'])
        command_line.extend(['-metadata:s:v:1', 'title=poster'])
        command_line.extend(['-metadata', 'title=%s' %
                             title, '-metadata', 'date=%s' % date])
        command_line.extend(['-c:a', 'copy'])
        command_line.extend(['-c:v', 'copy'])
        if self.packed_bframes:
            command_line.extend(['-bsf:v:0', 'mpeg4_unpack_bframes'])
        if out_ext == '.avi':
            command_line.extend(['-tag:v:0', 'xvid'])
        if out_ext == '.mp4':
            command_line.extend(['-movflags', '+faststart'])
        # man 8 ntfs-3g => windows_name
        # The forbidden characters are the nine characters " * / : < > ? \ |
        # ” ‹ › ⁎ ∕ ⑊ ＼︖ ꞉ ⏐
        forbidden_characters = '"*/:<>?\|'
        unicode_characters = '”⁎∕꞉‹›︖＼⏐'
        out_name = title.replace(' ', ' ')  # FIXME string copy
        for a, b in zip(forbidden_characters, unicode_characters):
            out_name = out_name.replace(a, b)
        out_file = os.path.join(
            self.output_dir, out_name + out_ext)
        command_line.extend([out_file])
        errcode, stdout, stderr = self.call_process(command_line)

    def convert(self):
        self._grab_info()
        self._check_info()
        self._check_genpts()
        self._check_packed_bframes()
        audio_stream = [stream for stream in self.ffprobe_data['streams']
                        if stream['codec_type'] == 'audio'][0]
        video_stream = [stream for stream in self.ffprobe_data['streams']
                        if stream['codec_type'] == 'video'][0]
        format_name = self.ffprobe_data['format']['format_name']
        # print(audio_stream)
        # print(video_stream)
        # print(format_name)
        # return
        if audio_stream['codec_name'] == 'aac' and video_stream['codec_name'] == 'h264':
            if format_name == 'matroska,webm':
                self._convert('.mp4')
            else:
                assert format_name == 'mov,mp4,m4a,3gp,3g2,mj2'
                self._convert('.mp4')
        else:
            assert format_name == 'matroska,webm' or format_name == 'avi'
            # convert to mkv for now
            self._convert('.mkv')

    def call_process(self, command_line_list, env=None, nolog=False, noerr=False):
        """ Thin wrapper over subprocess.call with logging functionality """
        self.logger.info(
            "Preparing to subprocess.call an external process with "
            "the following command line: %s ( %s )",
            command_line_list,
            " ".join(command_line_list))
        process = subprocess.Popen(command_line_list,
                                   stdin=subprocess.PIPE,
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE,
                                   shell=False,
                                   env=env)
        stdout, stderr = process.communicate()
        if sys.version_info[0] >= 3:  # Python 3
            stdout = stdout.decode("utf-8")
            stderr = stderr.decode("utf-8")
        binary = os.path.basename(command_line_list[0])
        errcode = process.returncode
        if errcode and not noerr:
            self._raise_exception("Process %s exited with error code %d.\nThe process stdout is \n%s\nstderror is \n%s" % (
                binary, errcode, stdout, stderr))
        else:
            if not nolog and stderr != '':
                self.logger.info("The process stderr is \n%s", stderr)
        return errcode, stdout, stderr

    def _get_logger(self):
        """ return a correctly setup logger """
        logger = logging.getLogger('nfofix')
        logger.setLevel(logging.DEBUG)
        ch = logging.StreamHandler()
        formatter = logging.Formatter(
            '%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        ch.setFormatter(formatter)
        ch.setLevel(logging.DEBUG)
        logger.addHandler(ch)
        return logger


def run(helper):
    logger = helper.logger
    helper.convert()


def main(args):
    # helper = FfmpegHelper(args.input, args.output)
    helper = FfmpegHelper(args.input)
    helper.set_verbose(args.verbose)
    run(helper)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="ffmpeg + nfo")
    parser.add_argument("input", help='input movie')
    parser.add_argument('output', nargs='?',
                        default='/tmp/dbg', help='output dir')
    # verbose
    parser.add_argument("--verbose",
                        help="verbose output", action='store_true')
    main(parser.parse_args())
